name: Validate PlantUML diagrams

on:
  push:
    paths:
      - '**/*.puml'
  pull_request:

jobs:
  validate-diagrams:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instala Java
      - name: Install Java
        run: sudo apt-get update && sudo apt-get install -y default-jre

      # Instala PlantUML
      - name: Install PlantUML
        run: sudo apt-get install -y plantuml

      # Valida diagramas
      - name: Validate diagrams
        run: |
          for file in $(find diagramas -name "*.puml"); do
            echo "Validando $file"
            plantuml -checkonly "$file"
          done